### PR TITLE
Delete govnocode

### PR DESCRIPTION
**Pull request by MIndLessForce**

### CODE REVIEW

**Comment by MIndLessForce** [comment]
faster please

**Comment by skorziro3000** [comment]
No

**Comment by MIndLessForce** [comment]
why

**Comment by MIndLessForce** [comment]
@skorziro3000 delet govnocod

**Comment by skorziro3000** [comment]
I'm don't accept with it!

**Comment by MIndLessForce** [comment]
AoAOoaAAoAoAOoaAAoAoAOoaAAoAoAOoaAAoAoAOoaAAo

**Comment by skorziro3000** [comment]
aoaooaoaaAOAOAoOAOOAOOooaOOAOA

**Pull request closed without merging**
